apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  type: NodePort
  selector:
    app: search-service
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: janjorquera/search-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: ELASTICSEARCH_URL
          value: "http://search-service-elasticsearch.default.svc.cluster.local:9200"
        - name: RABBITMQ_HOST
          value: message-broker
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /livez
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20