services:
  search_service:
    build: .  # Construye desde el Dockerfile en el directorio actual
    ports:
      - "8000:8000"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      RABBITMQ_HOST: "message_broker"  # Tu RabbitMQ externo
    depends_on:
      - elasticsearch
    networks:
      - Search_Service

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - Search_Service

volumes:
  es_data:

networks:
  Search_Service:
    external: true
