services:
  search_service:
    build: . # Builds from a Dockerfile in the current directory
    ports:
      - "8000:8000"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      RABBITMQ_HOST: "message_broker"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

networks:
  default:
    name: Search_Service
    external: true

volumes:
  es_data: